version: "3"

services:
  environment:
    image: immutag:0.0.4
    volumes:
      - ./:/immutag
      - immutag-cargo-data:/usr/local/cargo
      - nix-data:/nix
    tty: true

volumes:
 immutag-cargo-data:
  external: true
 nix-data:
  external: true
