version: "3"

services:
  environment:
    image: immutag:0.0.1
    volumes:
      - ./:/immutag
      - immutag-cargo-data:/usr/local/cargo
    tty: true

volumes:
 immutag-cargo-data:
  external: true
