#!/bin/bash

# Make sure to give host user read and write permission to ~/immutag
# $ suod chmod -R 777 ~/immutag

input="$@"
cmd=$(echo "$input" | cut -d " " -f 1)

sudo docker run -it \
-v "$HOME"/immutag:/root/immutag \
immutag:0.0.9 \
imt $input

if [ "$cmd" = "find" ];then
    # Need permissions to write in ~/immutag.
    rm $HOME/immutag/file > /dev/null 2>&1
    ln -s $(cat ~/immutag/.find_output | sed "s/\/root\/immutag/\/home\/$(whoami)\/immutag/g") $HOME/immutag/file
    echo "open symlink at ${HOME}/immutag/file"
fi
