#!/bin/bash

# Make sure to give host user read and write permission to ~/immutag
# $ suod chmod -R 777 ~/immutag

input="$@"
cmd=$(echo "$input" | cut -d " " -f 1)
cmd=$(echo "$input" | cut -d " " -f 1)

if [ "$cmd" = "add" ];then

    POSITIONAL=()
    while [[ $# -gt 0 ]]
    do
    key="$1"

    case $key in
        -n|--store-name)
        STORENAME="$2"
        shift # past argument
        shift # past value
        ;;
        --no-default-name)
        NODEFAULTNAME=YES
        shift # past argument
        ;;
        *)    # unknown option
        POSITIONAL+=("$1") # save it in an array for later
        shift # past argument
        ;;
    esac
    done
    set -- "${POSITIONAL[@]}" # restore positional parameters

    immutag_path="$HOME/immutag"

    input="$*"

    if [ -n "${STORENAME}" ];then
        name="$STORENAME"
    else
        name="main"
    fi

    file="$2"
    file_abs_path=$(eval realpath "$file")

    # Exit script here if we can't find the file to be added to the store.
    if [ ! -f "$file_abs_path" ];then
        echo "Can't find file, host."
        exit
    fi

    echo ""
    echo "abs path: $file_abs_path"
    echo "file: $file"

    cp "$file_abs_path" "$immutag_path"/stage/"$file"
fi

if [ "$cmd" = "update" ];then

    POSITIONAL=()
    while [[ $# -gt 0 ]]
    do
    key="$1"

    case $key in
        -n|--store-name)
        STORENAME="$2"
        shift # past argument
        shift # past value
        ;;
        *)    # unknown option
        POSITIONAL+=("$1") # save it in an array for later
        shift # past argument
        ;;
    esac
    done
    set -- "${POSITIONAL[@]}" # restore positional parameters

    addr="$2"
    file="$3"

    immutag_path="$HOME/immutag"

    if [ -n "${STORENAME}" ];then
	storename="$STORENAME"
    else
	storename="main"
    fi

    file="$3"
    file_abs_path=$(eval realpath "$file")

    # Exit script here if we can't find the file to be added to the store.
    if [ ! -f "$file_abs_path" ];then
        echo "Can't find file, host."
        exit
    fi

    # To add file name and extension to tag.
    fullfilename="$file"
    filename=$(basename "$fullfilename")
    fname="${filename%.*}"
    ext="${filename##*.}"

    echo ""
    echo "abs path: $file_abs_path"
    echo "file: $file"

    cp "$file_abs_path" "$immutag_path"/stage/"$fname"
fi

sudo docker run -it --rm \
-v "$HOME"/immutag:/root/immutag \
immutag:0.0.11 \
$input

if [ "$cmd" = "find" ];then
    # Need permissions to write in ~/immutag.
    rm $HOME/immutag/file > /dev/null 2>&1
    ln -s $(cat ~/immutag/.find_output | sed "s/\/root\/immutag/\/home\/$(whoami)\/immutag/g") $HOME/immutag/file
fi
