#!/usr/bin/env bash

mkdir -p -m 0755 $HOME/.local/bin
mkdir -m 0755 $HOME/.local/bin/immutag

cp /immutag/dev/cmd_add.sh $HOME/.local/bin/immutag/imt_add
cp /immutag/dev/cmd_init.sh $HOME/.local/bin/immutag/imt_init

cp /immutag/dev/_imt_add_file.sh $HOME/.local/bin/immutag/_imt_add_file
cp /immutag/dev/_imt_append_list.sh $HOME/.local/bin/immutag/_imt_append_list
cp /immutag/dev/_imt_new_index_addr.sh $HOME/.local/bin/immutag/_imt_new_index_addr
cp /immutag/dev/_imt_get_xpriv_from_wallet_info.sh $HOME/.local/bin/immutag/_imt_get_xpriv_from_wallet_info
cp /immutag/dev/_imt_get_bip44_address_from_xpriv.sh $HOME/.local/bin/immutag/_imt_get_bip44_address_from_xpriv
cp /immutag/dev/_imt_get_xpriv_from_wallet_info.sh $HOME/.local/bin/immutag/_imt_get_xpriv_from_wallet_info
cp /immutag/dev/_imt_json_parse_p2pkh_address.sh $HOME/.local/bin/immutag/_imt_json_parse_p2pkh_address
cp /immutag/dev/_imt_get_rid_of_quotation_marks.sh $HOME/.local/bin/immutag/_imt_get_rid_of_quotation_marks
cp /immutag/dev/_imt_bip44_info_derive_from_xpriv.sh $HOME/.local/bin/immutag/_imt_bip44_info_derive_from_xpriv
cp /immutag/dev/_imt_generate_from_24_word_mnemonic.sh $HOME/.local/bin/immutag/_imt_generate_from_24_word_mnemonic
cp /immutag/dev/_imt_write_wallet_info_file.sh $HOME/.local/bin/immutag/_imt_write_wallet_info_file
cp /immutag/dev/_imt_create_wallet_info_file_from_mnemonic.sh $HOME/.local/bin/immutag/_imt_create_wallet_info_file_from_mnemonic
