#!/usr/bin/env bash

mkdir -p -m 0755 $HOME/.local/bin
mkdir -m 0755 $HOME/.local/bin/immutag

cp imt.sh $HOME/.local/bin/imt
chmod +x $HOME/.local/bin/imt

cp cmd_add.sh $HOME/.local/bin/immutag/imt_add
cp cmd_init.sh $HOME/.local/bin/immutag/imt_init
cp cmd_tag_rm.sh $HOME/.local/bin/immutag/imt_tag_rm
cp cmd_find.sh $HOME/.local/bin/immutag/imt_find
cp cmd_find.sh $HOME/.local/bin/immutag/imt_find
cp cmd_tag_replace.sh $HOME/.local/bin/immutag/imt_tag_replace
cp cmd_tag_add.sh $HOME/.local/bin/immutag/imt_tag_add
cp cmd_commit_list.sh $HOME/.local/bin/immutag/imt_commit_list
cp cmd_commit_store.sh $HOME/.local/bin/immutag/imt_commit_store
cp cmd_commit.sh $HOME/.local/bin/immutag/imt_commit
cp cmd_rollback.sh $HOME/.local/bin/immutag/imt_rollback
cp cmd_rollforward.sh $HOME/.local/bin/immutag/imt_rollforward
cp cmd_gen_hash.sh $HOME/.local/bin/immutag/imt_gen_hash
cp cmd_list_gen_hash.sh $HOME/.local/bin/immutag/imt_list_gen_hash
cp cmd_commit.sh $HOME/.local/bin/immutag/imt_commit
cp cmd_update_file.sh $HOME/.local/bin/immutag/imt_update_file

cp _imt_append_list.sh $HOME/.local/bin/immutag/_imt_append_list
cp _imt_new_index_addr.sh $HOME/.local/bin/immutag/_imt_new_index_addr
cp _imt_get_xpriv_from_wallet_info.sh $HOME/.local/bin/immutag/_imt_get_xpriv_from_wallet_info
cp _imt_get_bip44_address_from_xpriv.sh $HOME/.local/bin/immutag/_imt_get_bip44_address_from_xpriv
cp _imt_get_xpriv_from_wallet_info.sh $HOME/.local/bin/immutag/_imt_get_xpriv_from_wallet_info
cp _imt_json_parse_p2pkh_address.sh $HOME/.local/bin/immutag/_imt_json_parse_p2pkh_address
cp _imt_get_rid_of_quotation_marks.sh $HOME/.local/bin/immutag/_imt_get_rid_of_quotation_marks
cp _imt_bip44_info_derive_from_xpriv.sh $HOME/.local/bin/immutag/_imt_bip44_info_derive_from_xpriv
cp _imt_generate_from_24_word_mnemonic.sh $HOME/.local/bin/immutag/_imt_generate_from_24_word_mnemonic
cp _imt_write_wallet_info_file.sh $HOME/.local/bin/immutag/_imt_write_wallet_info_file
cp _imt_create_wallet_info_file_from_mnemonic.sh $HOME/.local/bin/immutag/_imt_create_wallet_info_file_from_mnemonic
cp _imt_tag_rm.sh $HOME/.local/bin/immutag/_imt_tag_rm
cp _imt_tag_replace.sh $HOME/.local/bin/immutag/_imt_tag_replace
cp _imt_tag_add.sh $HOME/.local/bin/immutag/_imt_tag_add
cp _imt_print_list_only.sh $HOME/.local/bin/immutag/_imt_print_list_only
cp _imt_print_list_only.sh $HOME/.local/bin/immutag/_imt_print_list_only
cp _imt_update_list_store_hashes.sh $HOME/.local/bin/immutag/_imt_update_list_store_hashes
cp _imt_write_store_addrs.sh $HOME/.local/bin/immutag/_imt_write_store_addrs
cp _imt_exit_checkout.sh $HOME/.local/bin/immutag/_imt_exit_checkout
cp _imt_commit.sh $HOME/.local/bin/immutag/_imt_commit

chmod +x $HOME/.local/bin/immutag/*
