#!/usr/bin/env bash

mkdir -p -m 0755 $HOME/.local/bin
mkdir -m 0755 $HOME/.local/bin/immutag

mkdir /root/immutag_test/

# Copy test script into container's appropriate dir because shunit won't allow test script to change directory.
cp /immutag/dev/teardown_test.sh /root/immutag_test/
cp /immutag/dev/add_file_setup_test.sh /root/immutag_test/
cp /immutag/dev/add_tag_setup_test.sh /root/immutag_test/
cp /immutag/dev/tag_rm_setup_test.sh /root/immutag_test/
cp /immutag/dev/tag_replace_setup_test.sh /root/immutag_test/
cp /immutag/dev/init_setup_test.sh /root/immutag_test/
cp /immutag/dev/commit_setup_test.sh /root/immutag_test/
cp /immutag/dev/roll_setup_test.sh /root/immutag_test/

cp /immutag/dev/add_file_test.sh /root/immutag_test/
cp /immutag/dev/add_tag_test.sh /root/immutag_test/
cp /immutag/dev/tag_rm_test.sh /root/immutag_test/
cp /immutag/dev/tag_replace_test.sh /root/immutag_test/
cp /immutag/dev/init_test.sh /root/immutag_test/
cp /immutag/dev/commit_test.sh /root/immutag_test/
cp /immutag/dev/roll_test.sh /root/immutag_test/

chmod +x /root/immutag_test/*

cp /immutag/dev/cmd_add.sh $HOME/.local/bin/immutag/imt_add
cp /immutag/dev/cmd_init.sh $HOME/.local/bin/immutag/imt_init
cp /immutag/dev/cmd_tag_rm.sh $HOME/.local/bin/immutag/imt_tag_rm
cp /immutag/dev/cmd_find.sh $HOME/.local/bin/immutag/imt_find
cp /immutag/dev/cmd_find.sh $HOME/.local/bin/immutag/imt_find
cp /immutag/dev/cmd_tag_replace.sh $HOME/.local/bin/immutag/imt_tag_replace
cp /immutag/dev/cmd_tag_add.sh $HOME/.local/bin/immutag/imt_tag_add
cp /immutag/dev/cmd_commit_list.sh $HOME/.local/bin/immutag/imt_commit_list
cp /immutag/dev/cmd_commit_store.sh $HOME/.local/bin/immutag/imt_commit_store
cp /immutag/dev/cmd_commit.sh $HOME/.local/bin/immutag/imt_commit
cp /immutag/dev/cmd_rollback.sh $HOME/.local/bin/immutag/imt_rollback
cp /immutag/dev/cmd_rollforward.sh $HOME/.local/bin/immutag/imt_rollforward
cp /immutag/dev/cmd_gen_hash.sh $HOME/.local/bin/immutag/imt_gen_hash
cp /immutag/dev/cmd_list_gen_hash.sh $HOME/.local/bin/immutag/imt_list_gen_hash

cp /immutag/dev/_imt_add_file.sh $HOME/.local/bin/immutag/_imt_add_file
cp /immutag/dev/_imt_append_list.sh $HOME/.local/bin/immutag/_imt_append_list
cp /immutag/dev/_imt_new_index_addr.sh $HOME/.local/bin/immutag/_imt_new_index_addr
cp /immutag/dev/_imt_get_xpriv_from_wallet_info.sh $HOME/.local/bin/immutag/_imt_get_xpriv_from_wallet_info
cp /immutag/dev/_imt_get_bip44_address_from_xpriv.sh $HOME/.local/bin/immutag/_imt_get_bip44_address_from_xpriv
cp /immutag/dev/_imt_get_xpriv_from_wallet_info.sh $HOME/.local/bin/immutag/_imt_get_xpriv_from_wallet_info
cp /immutag/dev/_imt_json_parse_p2pkh_address.sh $HOME/.local/bin/immutag/_imt_json_parse_p2pkh_address
cp /immutag/dev/_imt_get_rid_of_quotation_marks.sh $HOME/.local/bin/immutag/_imt_get_rid_of_quotation_marks
cp /immutag/dev/_imt_bip44_info_derive_from_xpriv.sh $HOME/.local/bin/immutag/_imt_bip44_info_derive_from_xpriv
cp /immutag/dev/_imt_generate_from_24_word_mnemonic.sh $HOME/.local/bin/immutag/_imt_generate_from_24_word_mnemonic
cp /immutag/dev/_imt_write_wallet_info_file.sh $HOME/.local/bin/immutag/_imt_write_wallet_info_file
cp /immutag/dev/_imt_create_wallet_info_file_from_mnemonic.sh $HOME/.local/bin/immutag/_imt_create_wallet_info_file_from_mnemonic
cp /immutag/dev/_imt_tag_rm.sh $HOME/.local/bin/immutag/_imt_tag_rm
cp /immutag/dev/_imt_tag_replace.sh $HOME/.local/bin/immutag/_imt_tag_replace
cp /immutag/dev/_imt_tag_add.sh $HOME/.local/bin/immutag/_imt_tag_add
cp /immutag/dev/_imt_print_list_only.sh $HOME/.local/bin/immutag/_imt_print_list_only
cp /immutag/dev/_imt_print_list_only.sh $HOME/.local/bin/immutag/_imt_print_list_only
cp /immutag/dev/_imt_update_list_store_hashes.sh $HOME/.local/bin/immutag/_imt_update_list_store_hashes
cp /immutag/dev/_imt_write_store_addrs.sh $HOME/.local/bin/immutag/_imt_write_store_addrs
cp /immutag/dev/_imt_exit_checkout.sh $HOME/.local/bin/immutag/_imt_exit_checkout
cp /immutag/dev/_imt_commit.sh $HOME/.local/bin/immutag/_imt_commit

chmod +x $HOME/.local/bin/immutag/*
