#!/usr/bin/env bash

mkdir -p -m 0755 $HOME/.local/bin
mkdir -m 0755 $HOME/.local/bin/immutag

cp ../src/imt.sh $HOME/.local/bin/imt
chmod +x $HOME/.local/bin/imt

cp ../src/cmd_add.sh $HOME/.local/bin/immutag/imt_add
cp ../src/cmd_init.sh $HOME/.local/bin/immutag/imt_init
cp ../src/cmd_tag_rm.sh $HOME/.local/bin/immutag/imt_tag_rm
cp ../src/cmd_find.sh $HOME/.local/bin/immutag/imt_find
cp ../src/cmd_find.sh $HOME/.local/bin/immutag/imt_find
cp ../src/cmd_tag_replace.sh $HOME/.local/bin/immutag/imt_tag_replace
cp ../src/cmd_tag_add.sh $HOME/.local/bin/immutag/imt_tag_add
cp ../src/cmd_commit_list.sh $HOME/.local/bin/immutag/imt_commit_list
cp ../src/cmd_commit_store.sh $HOME/.local/bin/immutag/imt_commit_store
cp ../src/cmd_commit.sh $HOME/.local/bin/immutag/imt_commit
cp ../src/cmd_rollback.sh $HOME/.local/bin/immutag/imt_rollback
cp ../src/cmd_rollforward.sh $HOME/.local/bin/immutag/imt_rollforward
cp ../src/cmd_gen_hash.sh $HOME/.local/bin/immutag/imt_gen_hash
cp ../src/cmd_list_gen_hash.sh $HOME/.local/bin/immutag/imt_list_gen_hash
cp ../src/cmd_commit.sh $HOME/.local/bin/immutag/imt_commit
cp ../src/cmd_update_file.sh $HOME/.local/bin/immutag/imt_update_file
cp ../src/cmd_wormhole_send.sh $HOME/.local/bin/immutag/imt_wormhole_send
cp ../src/cmd_wormhole_recv.sh $HOME/.local/bin/immutag/imt_wormhole_recv

cp ../src/_imt_append_list.sh $HOME/.local/bin/immutag/_imt_append_list
cp ../src/_imt_new_index_addr.sh $HOME/.local/bin/immutag/_imt_new_index_addr
cp ../src/_imt_get_xpriv_from_wallet_info.sh $HOME/.local/bin/immutag/_imt_get_xpriv_from_wallet_info
cp ../src/_imt_get_bip44_address_from_xpriv.sh $HOME/.local/bin/immutag/_imt_get_bip44_address_from_xpriv
cp ../src/_imt_get_xpriv_from_wallet_info.sh $HOME/.local/bin/immutag/_imt_get_xpriv_from_wallet_info
cp ../src/_imt_json_parse_p2pkh_address.sh $HOME/.local/bin/immutag/_imt_json_parse_p2pkh_address
cp ../src/_imt_get_rid_of_quotation_marks.sh $HOME/.local/bin/immutag/_imt_get_rid_of_quotation_marks
cp ../src/_imt_bip44_info_derive_from_xpriv.sh $HOME/.local/bin/immutag/_imt_bip44_info_derive_from_xpriv
cp ../src/_imt_generate_from_24_word_mnemonic.sh $HOME/.local/bin/immutag/_imt_generate_from_24_word_mnemonic
cp ../src/_imt_write_wallet_info_file.sh $HOME/.local/bin/immutag/_imt_write_wallet_info_file
cp ../src/_imt_create_wallet_info_file_from_mnemonic.sh $HOME/.local/bin/immutag/_imt_create_wallet_info_file_from_mnemonic
cp ../src/_imt_tag_rm.sh $HOME/.local/bin/immutag/_imt_tag_rm
cp ../src/_imt_tag_replace.sh $HOME/.local/bin/immutag/_imt_tag_replace
cp ../src/_imt_tag_add.sh $HOME/.local/bin/immutag/_imt_tag_add
cp ../src/_imt_print_list_only.sh $HOME/.local/bin/immutag/_imt_print_list_only
cp ../src/_imt_print_list_only.sh $HOME/.local/bin/immutag/_imt_print_list_only
cp ../src/_imt_update_list_store_hashes.sh $HOME/.local/bin/immutag/_imt_update_list_store_hashes
cp ../src/_imt_write_store_addrs.sh $HOME/.local/bin/immutag/_imt_write_store_addrs
cp ../src/_imt_exit_checkout.sh $HOME/.local/bin/immutag/_imt_exit_checkout
cp ../src/_imt_commit.sh $HOME/.local/bin/immutag/_imt_commit

chmod +x $HOME/.local/bin/immutag/*
