#!/bin/bash


IMMUTAG_LAST_ADDR_INDEX_LAZY='eval cat $1 | tail -n 1 | cut -d " " -f 1'
IMMUTAG_LAST_ADDR_INDEX=$(eval $IMMUTAG_LAST_ADDR_INDEX_LAZY)
IMMUTAG_NEW_ADDR_INDEX=$((IMMUTAG_LAST_ADDR_INDEX+1))

echo $IMMUTAG_NEW_ADDR_INDEX
