#!/usr/bin/env bash

mkdir /root/immutag_test/

# Copy test script into container's appropriate dir because shunit won't allow test script to change directory.
cp /immutag/dev/teardown_test.sh /root/immutag_test/
cp /immutag/dev/add_file_setup_test.sh /root/immutag_test/
cp /immutag/dev/add_tag_setup_test.sh /root/immutag_test/
cp /immutag/dev/tag_rm_setup_test.sh /root/immutag_test/
cp /immutag/dev/tag_replace_setup_test.sh /root/immutag_test/
cp /immutag/dev/init_setup_test.sh /root/immutag_test/
cp /immutag/dev/commit_setup_test.sh /root/immutag_test/
cp /immutag/dev/roll_setup_test.sh /root/immutag_test/

cp /immutag/dev/add_file_test.sh /root/immutag_test/
cp /immutag/dev/add_tag_test.sh /root/immutag_test/
cp /immutag/dev/tag_rm_test.sh /root/immutag_test/
cp /immutag/dev/tag_replace_test.sh /root/immutag_test/
cp /immutag/dev/init_test.sh /root/immutag_test/
cp /immutag/dev/commit_test.sh /root/immutag_test/
cp /immutag/dev/roll_test.sh /root/immutag_test/

chmod +x /root/immutag_test/*
